version: '3'
services:
  app: &default
    build: .
    image: keboola/wr-db-snowflake-gcs
    environment:
      - KBC_RUNID
      - KBC_URL
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_PRIVATEKEY
      - DB_DATABASE
      - DB_SCHEMA
      - DB_WAREHOUSE
    links:
      - sshproxy
    volumes:
      - ssh-keys:/root/.ssh

  dev:
    <<: *default
    platform: linux/amd64 # explicitly set for arm64 developers (snowflake odbc is amd64 only)
    volumes:
      - .:/code
      - ./data:/data
      - ssh-keys:/root/.ssh

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh

volumes:
  ssh-keys:
